apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: sample-app
build:
  artifacts:
    - image: app
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - overlays/k3d-dev